### ISSUE TITLE
Extra ball appears!

### ISSUE THREAD

**Issue by hapiel** [jkboyce/jugglinglab#102]
I was surprised to see 4 balls in the 3 ball siteswap: `(4,3x)!(2,0)!(3x,0)!`

Maybe I understand something wrong about the `!` notation, but I think there should be no extra ball stuck in the left hand, no?
![(4,3x)!(2,0)!(3x,0)!](https://user-images.githubusercontent.com/4511993/150834758-e1b30464-723c-418d-9d74-b8c2681b1ce2.gif)

**Comment by jkboyce** [comment]
Ah, yes that does animate strangely. Short-beat patterns – where a hand is throwing on every beat, not every other beat – often need some adjusting to get right.

That is actually a 4-ball pattern, which we know from the average rule and the fact that it's 3 beats long:  (4 + 3 + 2 + 0 + 3 + 0) / 3 = 4. I always like to sketch a ladder diagram to see better what's going on. Something like this:

![ladder](https://user-images.githubusercontent.com/28497270/150950587-54edb9ed-3d1a-47ad-88c2-d74e4967e4ca.jpg)

Once the pattern is going (in the middle of the ladder), any vertical cut crosses 4 lines --> 4 ball pattern.

It animates oddly in Juggling Lab's default settings for two reasons:
- Juggling Lab by default interprets `2` throws as holds, since in the usual case a hand is throwing every 2 beats so the hand throwing the `2` won't be doing anything else before that ball is caught again. Now in a short-beat pattern that is not the case: One beat after the `2`, the left hand throws a `3x`. Juggling Lab just applies its default behavior for the `2` and holds it while it's making the `3x` throw, which makes it look like a multiplex throw.
- The # of dwell beats is too high. By default it uses `dwell=1.3` meaning a ball is caught 1.3 beats before it's thrown. In a short-beat pattern like this it only makes sense to have `dwell` less than 0.7 or so.

Here is what it looks like if we animate `pattern=(4,3x)!(2T,0)!(3x,0)!;dwell=0.7`:
![(4,3x)!(2T,0)!(3x,0)!](https://user-images.githubusercontent.com/28497270/150952831-f1f0d59b-bec1-471b-aa5e-ba9c430bc31b.gif)

Note this looks very similar to [`pattern=(8,6)(4,0)(6,0);bps=6`](https://jugglinglab.org/anim?pattern=(8,6)(4,0)(6,0);bps=6) which is the same pattern but with the beat duration halved so that we can write it in regular sync notation without the short beats.

Brainstorming now, I think how Juggling Lab could be improved here would be:
1. Don't interpret a `2` throw as a hold if that hand is making a throw on the next beat.
2. If the current `dwell` setting means that a ball will land such that there are other (short-beat) throws between that ball's catch and its subsequent throw, then move the catch later – after the intervening short-beat throw.

**Comment by hapiel** [comment]
Thanks for your detailed reply! You're absolutely right and I must have been sleeping while I wrote this pattern down as it is not a 3 ball pattern at all.

I was attempting to find a pattern that looked similar to `ss:3 hss:321`, but was for some reason not pleased with `242622` or `(1x,2)!(1x,3x)!(1x,1x)!` . But back to the drawing board it is!
