### ISSUE TITLE
Should throw timing be equaly spaced when using 1s?

### ISSUE THREAD

**Issue by hapiel** [jkboyce/jugglinglab#119]
In Juggling Lab, the timing of throws is always perfectly spaced, each throw taking an equal amount of time. This is not true my own juggling, I tend to space out the catches similarly, not the throws itself.

For example, a 441 where the catches have an even rhythm is very different from one where the throws have an even rhythm.

Pattern with even catching is attached, change extension back to .jml:
[441_even_catching_rhythm.txt](https://github.com/jkboyce/jugglinglab/files/8127752/441_even_catching_rhythm.txt)

Same goes for patterns like 531, or 51... They are rarely executed at an even throwing pace, even catching pace is much more comfortable but is rare for the 51 which goes more towards (4x,2x) of course. Similarly, the way I juggle 441 is maybe closer to `(4,0)!(1,3x)!1x*` than how Juggling Lab simulates it.

What do you think, should Juggling Lab approach reality, or stick with its current form of rhythmical perfection? I'm not sure what is more desirable.

**Comment by jkboyce** [comment]
This is a great point and something I intended to revisit. I agree the 1 throws are too late when they are thrown on-beat. Your JML version is how I juggle 441 too.

Here's my theory. Two factors cause human jugglers to throw 1s earlier than on-beat:
1. A 1 throw doesn't demand much in terms of accuracy or throw velocity, so a juggler doesn't need as much dwell time beforehand to properly execute it as compared with other throws (i.e. a 1 can be thrown early). Often in practice a 1 throw is a kind of shoveling motion toward the other hand–quick without much prep time needed.
2. A 1 throw is thrown on the next beat, so if we throw the 1 on-beat we're eating into the dwell time before the *next* throw, which is on-beat. For example if the 1 spends 0.3 beat in the air, then the next throw will only get 0.7 beats of dwell if we throw the 1 on-beat.

There is a place in the code [here](https://github.com/jkboyce/jugglinglab/blob/main/source/jugglinglab/notation/MHNPattern.java#L844) to adjust how many beats early 1s are thrown. I set it to 0 because I decided this isn't the correct model in all cases. For example, try 441 with `dwell=0.5` and (to my eye anyway) the on-beat 1 looks about right. (Notice that the catches here are uniformly-spaced, as in the 441 version you posted.)

*The "natural looking" thing, then, is to make the catches uniformly-spaced in time.* This rule makes sense when you think in terms of preserving the dwell time for the next throw. When `dwell` is greater than about 0.7 this means moving the 1 throws earlier than on-beat.

I'll work on this a bit. The key is to test all the various edge cases (very high/low dwell, short-beat patterns, etc.) to make sure those cases don't break and look ok. That can be tricky.

**Comment by froudaut** [comment]
@jboyce I think you are totally right and point 2 is particularly important when we have a height throw just after the 1. 
We need to find time to prepare the next throw in 771 for example. This is the main difficulty of this SS 

I juste made a pic a few days ago with a Dwell Time around 1 to fix things, and then a virtual flight time 0 for the 1 ;-).
![0x_case_1](https://user-images.githubusercontent.com/26428344/156077756-f77d5fa7-4270-40ef-b7f2-3cc755ded935.png)

According to Bruce Tiemann the Dwell Ratio done by most of the jugglers is between 0.3 and 0.7. 

Thus since this issue covers such behavior . What about the use of 0x in JL ? 
Mathematically it works, it will correspond to a kind of teleportation and some argues that it may be juggled however :
- either by slapping the object : I think in that case that the points you mention above are even worst. 
- or by a tierce person switching the object to simulate this teleportation.
![0x_case_2](https://user-images.githubusercontent.com/26428344/156078551-54fa3373-91bd-4610-b0d3-add49e8681b6.png)

**Comment by hapiel** [comment]
Speaking of teleporting and slapping:

I found some cases in juggling where a slap happens immediately after a zip. Practically on the same beat, of course. How that would translate to siteswap, I don't know, but it seemed relevant to the discussion. 
See a video and description of such a trick here: https://danielsimu.nl/research/posts/analyzing_tricks/#elbow-zip-in-out

The example slaps with the elbow, making it confusing for vanilla siteswap of course, but one could just as well imagine this to happen with the palm of the hand.

**Comment by hapiel** [comment]
So maybe what I think of as `441` is actually `(4,0)!(0x,4)!(0,1x)!*`? haha

**Comment by jkboyce** [comment]
Version 1.6.3 implements the feature discussed in this thread: `1` throws are now timed so that catches occur on an even rhythm.

**Comment by hapiel** [comment]
This is a huge step for the understanding of juggling timing! Thank you!
