### ISSUE TITLE
Certain siteswaps fail when permuted

### ISSUE THREAD

**Issue by georgievb** [jkboyce/jugglinglab#55]
The siteswap 01x(2,0)! works, but 1x(2,0)!0 and (2,0)!01x do not. The issue remains if the zero outside of the parentheses is replaced with a 3x.

**Comment by jkboyce** [comment]
Reasoning about these mixed sync/async patterns is tricky. The only way I can figure it out is to draw little spacetime diagrams on a grid. I've attached a drawing with these patterns plus some variations. In this case all patterns are 3 beats long.

Line 1 shows 01x(2,0)! which works fine: The beats on repetition 1 of the pattern that need balls fed in, are being fed by balls in repetition 2. So if you chain this out indefinitely the arrows will form continuous paths.

Line 2 shows the problem with 1x(2,0)!0: The arrows don't mesh together between repetition 1 and 2 of the pattern. Line 3 shows a version that works: 1x(0,2)!0. Note that by default Juggling Lab assigns the first beat in an async pattern (in this case a 1x throw) to the right hand. You can override this behavior to get a version of 1x(2,0)!0 that works, namely L1x(2,0)!0.

Line 4 shows the problem with (2,0)!01x. By default the 1x is assigned to the right hand (odd beats go to the right hand by default), but you could fix this with the L modifier as shown in line 5: (2,0)!0L1x

Also note that (2,0)!0 is in all cases equivalent to just (2,0) since there is an implied empty beat after every normal async throw. So for example (2,0)!0L1x = (2,0)L1x

![20190121-syncasync](https://user-images.githubusercontent.com/28497270/51497268-71426080-1d77-11e9-8f04-25503a4d9a84.jpg)
